/* ═══════════════════════════════════════════════════════════════
   GEV 中文增强包 —— 二级选项 / 控件全量字典（非侵入式）
   由 gev-cn.js 合并进主字典；删除 index.html 的引用即完全还原。
   收录：下拉选项、分段控件、参数滑杆标签、按钮与 tooltip。
   图标名(arrow_drop_down…)、dB 数值、CSS 颜色、地名/数据源名不收录。
   ═══════════════════════════════════════════════════════════════ */
export default {
  // ── 加载 / 状态 ──
  READY: '就绪',
  'RADIO READY': '电台就绪',
  RECORD: '录制',
  'SPACE MISSIONS — launches & orbital assets': '太空任务——发射与在轨资产',
  'Available Space Missions': '可用太空任务',
  'VISOR LOCK · ACTIVE': '护目锁定 · 已激活',
  'OPTICAL PLANE · 01': '光学平面 · 01',

  // ── 地图源 ──
  'Map source': '地图源',
  'Esri Satellite': 'Esri 卫星图',
  'Bing Aerial': 'Bing 航拍',
  'Bing Labels': 'Bing 标注',

  // ── 显示面板 · 选项 ──
  'HUD layout': 'HUD 布局',
  DISPLAY: '显示',
  'Detection Overlay (D)': '检测叠加层 (D)',
  'Detection overlay': '检测叠加层',
  'Detection fade distance': '检测淡出距离',
  'Detection label density': '检测标签密度',
  'Detection label allocation': '检测标签分配',
  'Detection opacity outside the keyhole': '取景孔外的检测不透明度',
  'Colour of the drawn shape': '绘制图形颜色',
  'Shape to draw': '绘制形状',
  'Label for the drawn shape': '绘制图形的标签',
  '3D model coverage': '3D 模型覆盖',
  '3D aircraft — flat icons zoomed out, 3D models up close':
    '3D 航空器——远看平面图标，近看 3D 模型',
  'World-overlay label and card opacity beyond the fade distance':
    '淡出距离之外的世界叠加层标签与卡片不透明度',
  'Intelligence HUD (H)': '情报 HUD (H)',
  Full: '完整',

  // ── 参数滑杆标签 ──
  Bloom: '泛光',
  'Bloom / Glow': '泛光 / 辉光',
  'Bloom intensity': '泛光强度',
  Sharpen: '锐化',
  Sharpening: '锐化',
  'Sharpen intensity': '锐化强度',
  Contrast: '对比度',
  Saturation: '饱和度',
  Vignette: '暗角',
  Grain: '颗粒',
  Scanlines: '扫描线',
  Distortion: '畸变',
  Pixelation: '像素化',
  'Edge Thickness': '边缘厚度',
  Sensitivity: '灵敏度',
  Instability: '不稳定度',
  'Glyph Density': '字符密度',
  OPACITY: '不透明度',
  Opacity: '不透明度',
  Rings: '环数',
  Range: '范围',
  Power: '强度',
  Sector: '扇区',
  'Sonar intensity': '声呐强度',
  'Sonar ring count': '声呐环数',
  'Sonar ring range': '声呐环距离',
  'Sonar sector width': '声呐扇区宽度',
  'Cyber sonar contact scanner': '赛博声呐接触目标扫描',
  'Cyber contact and label opacity': '赛博接触目标与标签不透明度',
  Scope: '取景',
  'Scope — the circular viewport mask': '取景——圆形视口遮罩',
  'Scope edge feather': '取景边缘羽化',
  'Scope edge feather as a percentage of the keyhole radius':
    '取景边缘羽化（占取景孔半径的百分比）',

  // ── 视觉风格说明（预设悬停/描述）──
  'Show the globe without a visual filter.': '显示无视觉滤镜的地球。',
  'Apply bright cel-shaded color and illustrated outlines.':
    '应用明亮的赛璐璐上色与描边。',
  'Apply high-contrast monochrome film-noir grading.':
    '应用高对比黑白黑色电影调色。',
  'Add a cold, snowy whiteout treatment to the scene.':
    '给场景叠加冷调雪白过曝效果。',
  'Simulate FLIR-style thermal contrast. Turn up Ironbow for color.':
    '模拟 FLIR 热成像对比。调高 Ironbow 以获得色彩。',

  // ── 命令坞 / 位置 ──
  'Search location by name or coordinates': '按名称或坐标搜索位置',
  'Navigation, voice, and visual preset controls': '导航、语音与视觉预设控制',
  Talk: '语音对话',
  VIEW: '视角',
  'View switcher': '视角切换',
  'USE VIEW': '使用视角',
  Pin: '标记',
  'Keep location tray open': '保持位置栏展开',
  'Keep visual presets open': '保持视觉预设展开',
  PLACES: '地点',
  CITIES: '城市',

  // ── 数据图层 / 监控 / 场景 ──
  'Remove every mark from the board': '清除面板上的所有标记',
  'Scene recipe': '场景配方',
  'CCTV camera': '监控摄像头',
  'CCTV feed frame': '监控画面框',
  'Camera pose — click a value to type': '镜头姿态——点击数值可直接输入',
  'Camera badges': '摄像头标记',
  Cameras: '摄像头',
  'SELECT BOX': '框选',
  'ALPR camera': '车牌识别摄像头',
  'AIS vessels': 'AIS 船舶',
  'Cyclones · NHC / CPHC': '气旋 · NHC / CPHC',
  'Public Safety': '公共安全',
  Infrastructure: '基础设施',
  Utilities: '公共事业',
  'Mapped installations': '已测绘设施',
  'Nearby cohort counts': '邻近同类计数',
  'Imagery days in the box': '框内影像天数',
  Events: '事件',
  News: '新闻',
  Email: '邮件',
  'Traffic / Transit': '交通 / 运输',
  'Aviation / Marine': '航空 / 航海',
  'Weather / Emergency': '天气 / 应急',
  'Latest regional news': '最新区域新闻',
  'Location-based information': '基于位置的信息',
  'Weather data by Open-Meteo.com': '天气数据来自 Open-Meteo.com',
  'Active weather products': '实时天气产品',
  'Advisory center / forecast track': '预警中心 / 预报路径',
  'Center-track uncertainty cone': '中心轨迹不确定锥',
  'Official advisory ↗': '官方预警 ↗',
  'Mean sea-level pressure': '海平面气压',
  '2 m air temperature': '2 米气温',
  'Wind speed': '风速',
  'Clouds only': '仅云层',
  'Read wind at map center': '读取地图中心风速',

  // ── 上下文 · 天气/新闻/事件 ──
  'Zoom level': '缩放级别',
  Wind: '风',
  Weather: '天气',

  // ── 电台（RADIO）──
  'Internet radio and local SDR': '网络电台与本地 SDR',
  'Local RTL-SDR receiver': '本地 RTL-SDR 接收机',
  'RTL-SDR receiver mode': 'RTL-SDR 接收模式',
  'RTL-SDR tuner gain for the current mode': '当前模式的 RTL-SDR 调谐增益',
  'Choose a different RTL-SDR or receiver channel':
    '选择其他 RTL-SDR 或接收通道',
  'Tune available internet radio stations': '调谐可用的网络电台',
  'Seek broadcast FM stations': '搜索调频广播电台',
  'Radio playback': '电台播放',
  'Radio volume': '电台音量',
  'Local SDR volume': '本地 SDR 音量',
  'Play selected radio station': '播放所选电台',
  'Play selected station': '播放所选电台',
  'Stop radio playback': '停止电台播放',
  'Next station': '下一个电台',
  'Previous station': '上一个电台',
  'Next filtered radio station': '下一个筛选电台',
  'Next filtered station': '下一个筛选电台',
  'Previous filtered radio station': '上一个筛选电台',
  'Previous filtered station': '上一个筛选电台',
  'Expand Radio': '展开电台',
  'Expand Radio section': '展开电台分区',
  'Open compact Radio controls': '展开紧凑电台控制',
  'Close compact Radio controls': '关闭紧凑电台控制',
  'Open detailed Radio controls': '打开详细电台控制',
  'Compact Radio controls': '紧凑电台控制',
  'Compact Radio volume': '紧凑电台音量',
  AUTO: '自动',
  Gain: '增益',
  Music: '音乐',
  STATION: '电台',
  HEARD: '已收听',
  POSITIONED: '已定位',
  SITE: '站点',
  COMMS: '通信',

  // ── 驾驶舱（COCKPIT）──
  'Aircraft cockpit view': '航空器驾驶舱视角',
  'Cockpit display options': '驾驶舱显示选项',
  'Cockpit display and Radio controls': '驾驶舱显示与电台控制',
  'Cockpit vision style': '驾驶舱视觉风格',
  'Cockpit Radio volume': '驾驶舱电台音量',
  'Cockpit briefing carousel': '驾驶舱简报轮播',
  'Cockpit briefing controls': '驾驶舱简报控制',
  'Cockpit briefing pages': '驾驶舱简报页面',
  'Cockpit compact Radio controls': '驾驶舱紧凑电台控制',
  'Expand Cockpit display options': '展开驾驶舱显示选项',
  'Expand Cockpit Radio controls': '展开驾驶舱电台控制',
  'Enable cockpit weather effects': '启用驾驶舱天气效果',
  'Current aircraft heading': '当前航空器航向',
  'Estimated flight plan': '推定飞行计划',
  'Estimated destination direction': '推定目的地方向',
  'Next cockpit vision style': '下一个驾驶舱视觉风格',
  'Previous cockpit vision style': '上一个驾驶舱视觉风格',
  'Next vision style': '下一个视觉风格',
  'Previous vision style': '上一个视觉风格',
  'Current cockpit vision style: NORMAL. Activate for next style.':
    '当前驾驶舱视觉风格：常规。点击切换下一个。',
  'Next briefing page': '下一页简报',
  'Previous briefing page': '上一页简报',
  'Reclassify as TR-3B': '重新归类为 TR-3B',
  'Reclassify tracked contact as TR-3B': '将追踪接触目标重新归类为 TR-3B',
  'Contact cockpit summary': '接触目标驾驶舱摘要',
  'Contact navigation': '接触目标导航',
  'Contact Context actions': '接触目标上下文操作',
  'Collapse Contact panel': '折叠接触目标面板',
  'Collapse contact panel': '折叠接触目标面板',
  'Collapse briefing panel': '折叠简报面板',
  'Collapse cockpit briefing panel': '折叠驾驶舱简报面板',
  'View switcher': '视角切换',

  // ── 画图 / 相机位姿输入 ──
  'Heading (compass °) — click to type': '航向（罗盘 °）——点击可输入',
  'Pitch (° up/down) — click to type': '俯仰（° 上下）——点击可输入',
  'Horizontal FOV (°) — click to type': '水平视场（°）——点击可输入',
  'Range / monitor-plane distance (m) — click to type':
    '距离 / 监视机距离（米）——点击可输入',
  'East offset from catalog position (m) — click to type':
    '相对星历位置的东向偏移（米）——点击可输入',
  'North offset from catalog position (m) — click to type':
    '相对星历位置的北向偏移（米）——点击可输入',
  'Mount height above ground (m) — click to type':
    '离地安装高度（米）——点击可输入',
  HDG: '航向',
  PITCH: '俯仰',
  RANGE: '距离',
  NAV: '导航',
  PATH: '路径',
  REGION: '区域',
  PLACES: '地点',
  UNITS: '单位',
  VISUAL: '视觉',
  IMAGE: '图像',
  BAND: '波段',
  TEMP: '气温',
  SKY: '天空',
  WIND: '风',
  WX: '天气',
  FLT: '飞行',
  HGT: '高度',
  'MSG/S': '消息/秒',
  FIRE: '火情',
  MIL: '军',
  MINI: '迷你',
  LOCAL: '本地',
  GEO: '地理',
  'DAILY OVERVIEW · 250 m': '每日概览 · 250 米',
  'MORE DETAIL · 30 m': '更高细节 · 30 米',
  'ALTITUDE · FT': '高度 · 英尺',
  'GROUND SPEED · KTS': '地速 · 节',
  'SOURCE LEVEL': '源层级',

  // ── 杂项按钮 / 提示 ──
  adjust: '调整',
  'Hide UI chrome': '隐藏界面边框',
  'Return UI controls': '恢复界面控件',
  'Globe actions': '地球操作',
  'View switcher': '视角切换',
  'Clear selected data layers': '清除已选数据图层',
  Clear: '清除',
  CLEAR: '清除',
  Standby: '待命',
  Contact: '接触目标',
  Expand: '展开',
  Details: '详情',
  Optional: '可选',

  // ── 场景（SCENE）· 面板与镜头卡片 ──
  LOAD: '加载',
  'No shots yet. Use CAPTURE SHOT to save current look.':
    '暂无镜头。点“截取镜头”保存当前画面。',
  'Double-click to rename': '双击重命名',
  'Shot name': '镜头名称',
  'New scene name': '新场景名称',
  'Scene action failed': '场景操作失败',
  Stopped: '已停止',
  'Stopped (Esc)': '已停止 (Esc)',

  // ── 场景 / 镜头 标题（内置示例配方）──
  'Bhote Koshi Evidence Sequence': '博特科西 · 证据序列',
  'Bhote Koshi Regional Approach': '博特科西 · 区域接近',
  'Bhote Koshi Nearby Cities': '博特科西 · 邻近城镇',
  'Bhote Koshi Incident Corridor': '博特科西 · 事件走廊',
  'Bhote Koshi Flood Path': '博特科西 · 洪水路径',
  'Bhote Koshi Corridor Overview': '博特科西 · 走廊概览',
  'Bhote Koshi Upper Valley': '博特科西 · 上游河谷',
  'Global Incident Context': '全球事件态势',
  'Nepal-Focused Globe Rotation': '尼泊尔焦点环球旋转',
  'Upper Valley Collapse': '上游河谷崩塌',
  'Nepal-China Border Gate': '尼中边境口岸',
  'Nepal Flood Incident': '尼泊尔洪水事件',
  'Bidur / Trishuli Consequence': '比杜尔 / 特里苏里 · 后果',
  'City Overload': '城市过载',
  'Debris-Dammed Lake': '堰塞湖',
  'Global Flights Radar': '全球航班雷达',
  'Omniscience Pullback': '全知拉远',
  'Orbital Watch': '在轨监视',
  'Syabru Besi Passage': '夏布鲁贝西 · 通道',
  'Thermal Threat Board': '热成像威胁面板',
  'Timure Evidence Cluster': '蒂穆雷 · 证据簇',

  // ── 镜头元数据 · 风格 ID 与检测模式 ──
  RETRO: '绿屏 CRT',
  Amber: '琥珀',
  Ghost: '幽灵',
  Ironbow: '铁红',
  'X-Ray': 'X光',
  Cinema: '电影',
  SURVEILLANCE: '夜视仪',
  THERMAL: '热成像',
  SPARSE: '稀疏',
  BALANCED: '均衡',
  DENSE: '密集',

  // ── 数据图层名（全量）──
  'ALPR Cameras': '车牌识别摄像头',
  Bikeshare: '共享单车',
  'Bike Share': '共享单车',
  CCTV: '监控',
  'Cyclone advisories': '气旋预警',
  'Daily overview': '每日概览',
  Directions: '路线',
  'Earthquakes (24h)': '地震（24 小时）',
  'Fire Perimeters': '火场边界',
  'Global Context': '全球态势',
  'Google Maps Places': 'Google 地图地点',
  'Live AIS Vessels': '实时 AIS 船舶',
  'Mapped Installations': '已测绘设施',
  'Mapped ALPR Cameras': '已测绘车牌识别摄像头',
  'Data Centers': '数据中心',
  'Active Fires': '活跃火点',
  'Space Missions (30d)': '太空任务（30 天）',
  'Street Traffic': '街道交通',
  'Submarine Cables': '海底光缆',
  'Military Installations': '军事设施',
  Cameras: '摄像头',

  // ── 图层数据状态徽标 ──
  LOADING: '加载中',
  DEGRADED: '降级',
  STALE: '陈旧',
  PARTIAL: '部分',
  FALLBACK: '回退',
  UNAVAILABLE: '不可用',

  // ── 上下文 / RADIO / 语音 状态 ──
  'CONTACTS — nearest planes · vessels · sites':
    '接触目标——最近的飞机 · 船舶 · 设施',
  'Choose a globe marker or use next.': '在地球上选一个标记，或点“下一个”。',
  CONNECTING: '连接中',
  LISTENING: '收听中',
  STREAMING: '串流中',
  'OFF AIR': '停播',
  STOPPED: '已停止',
  'Hold Space to talk': '按住空格说话',
  'Release Space to send': '松开空格发送',
  'Requesting microphone': '正在请求麦克风',
  'Toggle voice control': '切换语音控制',
  'Activate to toggle voice': '点击切换语音',
  'Ask or command': '提问或下达指令',
  Pause: '暂停',
  Resume: '继续',
  'Latest observation': '最新观测',
  'Earlier observation': '更早观测',
  'Later observation': '更晚观测',
  'Observed history': '已观测历史',
  'Replay observed history': '回放已观测历史',
  'Next story beat': '下一个情节',
  'Previous story beat': '上一个情节',
  Mode: '模式',
  Home: '主页',
  Close: '关闭',
  Show: '显示',
  'COLLAPSE VIEWPOINT': '折叠视角',
  'AUTOPLAY BLOCKED · USE PROVIDER CONTROLS': '自动播放被拦截 · 请用服务方控件',
  'Free key — register, paste, done': '免费 key——注册、粘贴、完成',

  // ── 生命周期 / 连接 徽标 ──
  ENABLING: '启用中',
  ENABLED: '已启用',
  DISABLING: '停用中',
  DISABLED: '已禁用',
  DISABLE: '禁用',
  SYNCING: '同步中',
  WAITING: '等待中',
  SEARCHING: '搜索中',
  CONNECTED: '已连接',
  DISCONNECTED: '已断开',
  DISCONNECT: '断开',
  REFRESHING: '刷新中',
  'STALE FEED': '陈旧数据源',
  'LOAD FAILED': '加载失败',
  'LOAD COMPLETE': '加载完成',
  'NO FEED': '无数据源',
  'NO CALLSIGN': '无呼号',
  'NO FIX': '无定位',
  'NO STATIONS': '无电台',
};
